CC=gcc
CFLAGS=-std=c11 -Wall -Wextra -pedantic -g

hello: hello.c
	$(CC) -o hello hello.c $(CFLAGS)

table: table.c
	$(CC) -o table table.c $(CFLAGS)

capitalize: capitalize.c
	$(CC) -o capitalize capitalize.c $(CFLAGS)

array: array.c
	$(CC) -o array array.c $(CFLAGS)
